CREATE TABLE scheme_status (
  sr_no INTEGER,
  scheme_id TEXT NOT NULL,
  region TEXT,
  circle TEXT,
  division TEXT,
  sub_division TEXT,
  block TEXT,
  scheme_name TEXT NOT NULL,
  agency TEXT,
  number_of_village INTEGER,
  total_villages_integrated INTEGER,
  no_of_functional_village INTEGER,
  no_of_partial_village INTEGER,
  no_of_non_functional_village INTEGER,
  fully_completed_villages INTEGER,
  total_number_of_esr INTEGER,
  scheme_functional_status TEXT,
  total_esr_integrated INTEGER,
  no_fully_completed_esr INTEGER,
  balance_to_complete_esr INTEGER,
  flow_meters_connected INTEGER,
  pressure_transmitter_connected INTEGER,
  residual_chlorine_analyzer_connected INTEGER,
  fully_completion_scheme_status TEXT,
  mjp_commissioned TEXT,
  mjp_fully_completed TEXT,
  dashboard_url TEXT
  -- No primary key - allows multiple entries with the same scheme_id and block
);